version: "3"
services:

  jupyter:
    image: python_NAMEglycemic:latest
    user: root
    environment:
      NB_UID=1001
      NB_GID=1001
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    working_dir: /home/jovyan/NAME
    volumes:
          - ".:/home/jovyan/NAME"
          - "./src:/home/jovyan/NAME/src"
          - "./test:/home/jovyan/NAME/test"
          - "./data:/home/jovyan/NAME/data"
          - "./jupyter:/home/jovyan/NAME/jupyter"
    environment:
          - JUPYTER_ENABLE_LAB=yes
